### ISSUE TITLE
Deploy won't update existing micro bosh

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-community/bosh-bootstrap#163]
While running `bosh-bootstrap deploy` I get the following output

```
Deployment previously failed to complete. Deleting and deploying micro BOSH microbosh-openstack again.

You are going to delete micro BOSH deployment `microbosh-openstack'.

THIS IS A VERY DESTRUCTIVE OPERATION AND IT CANNOT BE UNDONE!
```

I quickly canceled `crtl-c` and investigated the problem.

```
cd /var/vcap/store/microboshes/deployments
cat bosh-deployments.yml | yaml get instances -j
```

``` yaml
[
  {
    "vm_cid": "66eb6904-2d4a-4022-b739-d288070adf89", 
    "uuid": "bm-1b171c31-6195-42d0-a0f4-8230449aeb6f", 
    "stemcell_cid": "7c2f7612-085a-461c-9a36-17f2610f813d", 
    "disk_cid": "31", 
    "id": 1, 
    "stemcell_name": "micro-bosh-stemcell-openstack-kvm-1.5.0.pre2", 
    "name": "microbosh-openstack"
  }
]
```
