### ISSUE TITLE
clean Highline values before setting

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/bosh-bootstrap#194]
/cc @ramonskie 

``` yaml

---
bosh:
  name: firstbosh
provider:
  name: openstack
  credentials:
    openstack_username: !str:HighLine::String test
    openstack_api_key: !str:HighLine::String test
    openstack_tenant: !str:HighLine::String test
    openstack_auth_url: !str:HighLine::String http://myurl.com/v2.0/tokens
  region: !str:HighLine::String
```
