### ISSUE TITLE
Configure microbosh.dns/registry to be the floating IP

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/bosh-bootstrap#232]
```
apply_spec:
  properties:
    director:
      max_threads: 3
    hm:
      resurrector_enabled: true
    ntp:
      - 0.north-america.pool.ntp.org
      - 1.north-america.pool.ntp.org
      - 2.north-america.pool.ntp.org
      - 3.north-america.pool.ntp.org
    dns:
      address: 75.55.106.18
    registry:
      address: 75.55.106.182
```
