### ISSUE TITLE
[openstack] num_threads: 3

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/bosh-bootstrap#237]
Use the micro_bosh.yml ideas from @frodenas's docs http://docs.cloudfoundry.com/docs/running/deploying-cf/openstack/deploying_microbosh.html

``` yaml
  properties:
    director:
      max_threads: 3
    hm:
      resurrector_enabled: true
    ntp:
      - 0.north-america.pool.ntp.org
      - 1.north-america.pool.ntp.org
```
