### ISSUE TITLE
openstack micro_bosh.yml changes

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/bosh-bootstrap#248]
From http://docs.cloudfoundry.com/docs/running/deploying-cf/openstack/deploying_microbosh.html

```
  properties:
    director:
      max_threads: 3
    hm:
      resurrector_enabled: true
    ntp:
      - 0.north-america.pool.ntp.org
      - 1.north-america.pool.ntp.org
```
