### ISSUE TITLE
If targeting non-default VPC, microbosh not targeting correct VPC

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/bosh-bootstrap#285]
No mention in micro_bosh.yml of subnets & vpcs:

``` yaml

---
name: firstbosh
logging:
  level: DEBUG
network:
  type: dynamic
  vip: 10.10.0.36
...
```

Instead:

``` yaml
network:
  type: manual
  #vip: 54.200.124.155
  ip: 10.10.0.38
  dns:
  - 10.10.0.2
  cloud_properties:
    subnet: subnet-2013cd45

```
