### ISSUE TITLE
Deployer: Connection Timed out while waiting for agent 

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-community/bosh-bootstrap#58]
After creating micro BOSH vm, when waiting for the agent, the following error shows up in bosh_micro_deploy.log on the inception vm:

> #<Errno::ETIMEDOUT: Connection timed out - connect(2)>

This can be traced back to a problem with the network settings as set in micro_bosh.yml

bosh-bootstrap sets the following config:

``` yaml
network:
  type: dynamic
  vip: {public_ip}
```

The settings that work in our case are:

``` yaml
network:                                                                                                                                                                                   
    name: default                                                                                                                                                                            
    type: dynamic                                                                                                                                                                            
    label: {label_name}                                                                                                                                                                        
    ip: {public_ip}  
```

Source: https://github.com/cloudfoundry/oss-docs/blob/master/bosh/documentation/install_microbosh_openstack.md#create-manifest-file
